#ifndef HAND_FOLLOWING_MODE_H
#define HAND_FOLLOWING_MODE_H

#define HAND_FOLLOW_TARGET_DISTANCE 20
#define HAND_FOLLOW_TOLERANCE 3
#define HAND_FOLLOW_EMERGENCY_DISTANCE 8
#define HAND_FOLLOW_MIN_SPEED 50
#define HAND_FOLLOW_MAX_SPEED 140
#define HAND_FOLLOW_NOISE_JUMP_CM 15
#define HAND_FOLLOW_SAMPLE_COUNT 5

void updateHandFollowingMode();

#endif
